name: build

on: [workflow_dispatch,push]

env:
  DOTNET_VERSION: '6.0.402' # The .NET SDK version to use
  PROJECT_NAME: CMI.rca_gtm_synergy_suite_ServBoHExtInventarioTrasladoSS
  PROJECT_KEY: CMI.rca_gtm_synergy_suite_ServBoHExtInventarioTrasladoSS
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_URL: https://codequality.softwareone.com/
  IP_DEPLOY: ${{secrets.IP_DEPLOY}}
  USERNAME_DEPLOY: ${{secrets.USERNAME_DEPLOY}}
  PASSWORD_DEPLOY: ${{secrets.PASSWORD_DEPLOY}}
  BASE: C:\CMI
  DIRECTORYDESTINY: deploy

jobs:
  deploy:
    runs-on: windows-latest
    name: deploy
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Output contents
        shell: powershell
        run: |
          ./testParameters.ps1 ${{ env.SONAR_TOKEN }} ${{env.USERNAME_DEPLOY}} ${{env.BASE}} ${{ env.IP_DEPLOY }} ${{ env.USERNAME_DEPLOY }}
          